### ISSUE TITLE
Task.3 データベース設計

### ISSUE THREAD

**Issue by koichi-oshima** [koichi-oshima/qiita_clone#5]
# ER図ツール
http://bashalog.c-brains.jp/18/02/14-144444.php

**Comment by koichi-oshima** [comment]
# ER図
![IMG-0436](https://user-images.githubusercontent.com/35131508/81403584-b35f0380-916e-11ea-83b9-5fcb1b5c3a1a.JPG)

# 補足
artilcleテーブルのpublicは下書きか判定するのに利用できるかと思いました。

**Comment by yuta-ushijima** [comment]
publicをtrue/falseで切り替えると状態を管理できるという意図は汲めますが、statusとかの方がよりわかりやすいのでベターかなと思いました！
それ以外は良さそうです！

**Comment by koichi-oshima** [comment]
確かにステータスの方が分かり易いですね！！
ご指摘ありがとうございます！！
